import { logError } from '../observability/logger';
import { supabaseAdmin } from '@/lib/supabase';
import type { AIContext } from './policy';
export async function reserveBudget(input: { context: AIContext; requestId: string; provider: string; model: string; inputTokens: number; maxOutputTokens: number }) {
  if (input.context.scope !== 'customer') return { allowed: true, enforce: false, reservedTokens: input.inputTokens + input.maxOutputTokens };
  const mode = process.env.AI_BUDGET_MODE === 'enforce' ? 'enforce' : 'observe';
  try { const { data, error } = await supabaseAdmin.rpc('reserve_ai_budget', { client_id_input: input.context.clientId, feature_input: input.context.feature, request_id_input: input.requestId, provider_input: input.provider, model_input: input.model, estimated_input_tokens: input.inputTokens, max_output_tokens: input.maxOutputTokens, enforce_input: mode === 'enforce' }); if (error) throw error; const row = Array.isArray(data) ? data[0] : data; return { allowed: row?.allowed !== false, enforce: mode === 'enforce', id: row?.reservation_id, reservedCostMicros: row?.reserved_cost_micros || 0, reservedTokens: row?.reserved_tokens || input.inputTokens + input.maxOutputTokens }; }
  catch (error) { logError('[AI budget] reservation check unavailable', error instanceof Error ? error.message : 'unknown'); return mode === 'enforce' ? { allowed: false, enforce: true, reservedTokens: 0 } : { allowed: true, enforce: false, reservedTokens: input.inputTokens + input.maxOutputTokens }; }
}
export async function settleBudget(id: string | undefined, input: { inputTokens: number; outputTokens: number; status: 'settled' | 'expired_charged' | 'released' }) { if (!id) return; try { const { data, error } = await supabaseAdmin.rpc('settle_ai_budget', { reservation_id_input: id, input_tokens_input: input.inputTokens, output_tokens_input: input.outputTokens, status_input: input.status }); if (error || data === false) logError('[AI budget] settlement rejected', error?.message || 'rpc returned false'); } catch (error) { logError('[AI budget] settlement failed', error instanceof Error ? error.message : 'unknown'); } }
