import { createClient } from '@supabase/supabase-js';
import { redactSensitive } from '@/lib/observability/redact';
const supabase = createClient(process.env.NEXT_PUBLIC_SUPABASE_URL || 'https://placeholder-project.supabase.co', process.env.SUPABASE_SERVICE_ROLE_KEY || 'placeholder-service-key');
interface LLMLogInput { client_id?: string; session_id?: string; deal_id?: string; feature: string; model_used?: string; prompt_version?: string; metadata?: Record<string, unknown>; latency_ms?: number; input_tokens?: number; output_tokens?: number }
export async function logLLMCall(data: LLMLogInput): Promise<void> {
  supabase.from('llm_logs').insert({ client_id: data.client_id, session_id: data.session_id, deal_id: data.deal_id, feature: data.feature, model_used: data.model_used ?? process.env.TOGETHER_MODEL ?? 'moonshotai/Kimi-K2.6', prompt_version: data.prompt_version ?? 'v1.0', metadata: redactSensitive(data.metadata ?? {}), latency_ms: data.latency_ms, input_tokens: data.input_tokens, output_tokens: data.output_tokens, record_type: 'interaction' }).then();
}
export interface AIProviderAttemptLog { client_id?: string; feature: string; scope: 'customer' | 'internal'; provider: string; operation: 'chat' | 'embedding'; model: string; request_id: string; attempt: number; fallback_used: boolean; status: string; latency_ms: number; input_tokens: number; output_tokens: number; estimated_cost_micros?: number; usage_source?: string; finish_reason?: string; reservation_id?: string; error_code?: string }
export async function logAIProviderAttempt(data: AIProviderAttemptLog): Promise<void> { supabase.from('llm_logs').insert({ client_id: data.client_id, feature: data.feature, model_used: data.model, metadata: {}, scope: data.scope, latency_ms: data.latency_ms, input_tokens: data.input_tokens, output_tokens: data.output_tokens, estimated_cost_micros: data.estimated_cost_micros ?? null, usage_source: data.usage_source ?? null, finish_reason: data.finish_reason ?? null, record_type: 'provider_attempt', provider: data.provider, operation: data.operation, request_id: data.request_id, attempt: data.attempt, fallback_used: data.fallback_used, status: data.status, reservation_id: data.reservation_id, error_code: data.error_code }).then(); }
