'use client';
import { useEffect, useState } from 'react';
const usd = (value: unknown) => `$${(Number(value || 0) / 1_000_000).toFixed(4)}`;
export default function AICostsPage() {
  const [data, setData] = useState<any>(null); const [error, setError] = useState('');
  useEffect(() => { const passkey = localStorage.getItem('founder_passkey') || ''; fetch('/api/founder/ai-costs', { headers: { Authorization: `Bearer ${passkey}` } }).then(async r => { const body = await r.json(); if (!r.ok) throw new Error(body.error || 'Unable to load'); setData(body); }).catch(e => setError(e.message)); }, []);
  if (error) return <main className="min-h-screen bg-[#080B0F] text-white p-8"><p className="text-red-300">{error}</p></main>;
  const usage = data?.usage || {}; const reliability = data?.reliability || {}; const attempts = Number(usage.successful_attempts || 0) + Number(usage.failed_attempts || 0); const successRate = attempts ? `${Math.round(Number(usage.successful_attempts || 0) / attempts * 100)}%` : '—';
  return <main className="min-h-screen bg-[#080B0F] text-white p-8"><div className="max-w-6xl mx-auto"><a href="/founder" className="text-[#C2683D] text-sm">← Founder console</a><h1 className="text-2xl font-bold mt-6">AI cost & reliability</h1><p className="text-sm text-gray-400 mt-1">Estimated provider cost; not invoice truth.</p><div className="grid grid-cols-2 md:grid-cols-6 gap-4 mt-8">{[['Estimated cost', usd(usage.estimated_cost_micros)],['Input tokens', Number(usage.input_tokens || 0).toLocaleString()],['Output tokens', Number(usage.output_tokens || 0).toLocaleString()],['Success rate', successRate],['Timeouts', Number(reliability.timeout_attempts || 0).toLocaleString()],['Unpriced', Number(reliability.unpriced_attempts || 0).toLocaleString()]].map(([label,value])=><div key={label as string} className="border border-[#1e293b] rounded-lg p-4"><p className="text-xs text-gray-400">{label}</p><p className="text-xl mt-2">{value}</p></div>)}</div><p className="text-xs text-gray-500 mt-3">Fallback attempts: {reliability.fallback_attempts || 0}. Unpriced calls are explicitly counted rather than shown as real dollars.</p><section className="mt-8"><h2 className="text-lg font-semibold">By customer</h2><div className="overflow-auto mt-3"><table className="w-full text-sm"><thead><tr className="text-left text-gray-400"><th className="p-2">Company</th><th className="p-2">Plan</th><th className="p-2">Estimated spend</th><th className="p-2">Cost use</th><th className="p-2">Token use</th><th className="p-2">Denied</th></tr></thead><tbody>{(data?.by_client || []).map((row:any)=>{ const costPct = row.cost_limit_micros ? Math.round(Number(row.estimated_cost_micros || 0) / Number(row.cost_limit_micros) * 100) : 0; const tokenPct = row.token_limit ? Math.round((Number(row.input_tokens || 0)+Number(row.output_tokens || 0)) / Number(row.token_limit) * 100) : 0; return <tr key={row.id} className="border-t border-[#1e293b]"><td className="p-2">{row.company_name || row.id}</td><td className="p-2">{row.plan || '—'}</td><td className="p-2">{usd(row.estimated_cost_micros)}</td><td className="p-2">{costPct}%</td><td className="p-2">{tokenPct}%</td><td className="p-2">{row.denied_attempts || 0}</td></tr>})}</tbody></table></div></section><section className="mt-8"><h2 className="text-lg font-semibold">By feature</h2><pre className="mt-3 text-xs text-gray-300 whitespace-pre-wrap">{JSON.stringify(data?.by_feature || [], null, 2)}</pre></section><section className="mt-8"><h2 className="text-lg font-semibold">By model</h2><pre className="mt-3 text-xs text-gray-300 whitespace-pre-wrap">{JSON.stringify(data?.by_model || [], null, 2)}</pre></section></div></main>;
}
