import Link from 'next/link';
import { ArrowDownRight, ArrowRight, BarChart3, Check, Globe2, Radar, Sparkles, Waypoints } from 'lucide-react';
import { ChurnautMark } from '@/components/brand/ChurnautMark';

const steps = [
  { number: '01', title: 'Observe', copy: 'Capture the context behind every visit: source, account, intent, and momentum.', icon: Radar, tone: 'public-step-observe' },
  { number: '02', title: 'Decide', copy: 'Translate that context into rules your team can understand, inspect, and improve.', icon: Waypoints, tone: 'public-step-activate' },
  { number: '03', title: 'Adapt', copy: 'Serve the right message, route, or rep while the opportunity is still warm.', icon: Sparkles, tone: 'public-step-positive' },
];

export default function Home() {
  return (
    <main className="public-home min-h-screen bg-[var(--field-canvas)] text-[var(--field-ink)] selection:bg-[var(--signal-primary)]/20">
      <header className="public-home-header mx-auto flex w-full max-w-[1440px] items-center justify-between px-6 py-6 sm:px-10 lg:px-14">
        <ChurnautMark href="/" />
        <nav className="flex items-center gap-3 sm:gap-5" aria-label="Primary">
          <Link href="/login" className="rounded-full px-3 py-2 text-xs font-semibold text-[var(--field-ink-secondary)] transition hover:bg-white/70 hover:text-[var(--field-ink)]">SIGN IN</Link>
          <Link href="/signup" className="inline-flex min-h-10 items-center gap-2 rounded-full bg-[var(--field-ink)] px-4 py-2 text-xs font-semibold tracking-[0.04em] text-white shadow-lg shadow-black/10 transition motion-safe:hover:-translate-y-0.5 hover:bg-[var(--signal-primary)]">GET STARTED <ArrowRight className="h-3.5 w-3.5" aria-hidden="true" /></Link>
        </nav>
      </header>

      <section className="public-home-hero mx-auto grid w-full max-w-[1440px] gap-12 px-6 pb-20 pt-12 sm:px-10 md:pt-20 lg:grid-cols-[0.95fr_1.05fr] lg:items-start lg:gap-20 lg:px-14 lg:pb-24">
        <div className="public-home-hero-copy max-w-2xl">
          <div className="inline-flex items-center gap-2 rounded-full border border-[var(--signal-primary)]/25 bg-[var(--signal-primary-soft)] px-3 py-1.5 font-mono text-[10px] font-semibold uppercase tracking-[0.16em] text-[var(--signal-primary)]"><span className="h-1.5 w-1.5 rounded-full bg-[var(--signal-positive)]" /> Real-time revenue signals</div>
          <h1 className="public-home-display mt-8 max-w-[11ch] text-[clamp(3.2rem,7vw,6.8rem)] font-semibold leading-[0.92] tracking-[-0.075em] text-[var(--field-ink)]">Make the next move obvious.</h1>
          <p className="mt-8 max-w-xl text-base leading-7 text-[var(--field-ink-secondary)] sm:text-lg">Churnaut turns web intent, CRM context, and routing logic into a better experience for the accounts that matter most.</p>
          <div className="mt-9 flex flex-col gap-3 sm:flex-row"><Link href="/signup" className="inline-flex min-h-12 items-center justify-center gap-3 rounded-full bg-[var(--signal-primary)] px-6 text-sm font-semibold text-white shadow-xl shadow-[var(--signal-primary)]/15 transition motion-safe:hover:-translate-y-0.5 hover:bg-[var(--signal-primary-strong)]">Initialize workspace <ArrowRight className="h-4 w-4" /></Link><Link href="/login" className="inline-flex min-h-12 items-center justify-center rounded-full border border-[var(--field-line-strong)] bg-[var(--field-surface)] px-6 text-sm font-semibold text-[var(--field-ink-secondary)] transition motion-safe:hover:-translate-y-0.5 hover:border-[var(--signal-primary)] hover:text-[var(--field-ink)]">Access dashboard</Link></div>
          <div className="mt-10 flex flex-wrap gap-x-6 gap-y-2 text-xs text-[var(--field-ink-muted)]"><span className="inline-flex items-center gap-2"><Check className="h-3.5 w-3.5 text-[var(--signal-positive)]" /> Install once, learn continuously</span><span className="inline-flex items-center gap-2"><Check className="h-3.5 w-3.5 text-[var(--signal-positive)]" /> CRM-aware routing</span><span className="inline-flex items-center gap-2"><Check className="h-3.5 w-3.5 text-[var(--signal-positive)]" /> Built for revenue teams</span></div>
        </div>

        <div className="public-home-hero-visual relative min-w-0" data-hero-visual="true">
          <div className="public-home-decoration-layer" aria-hidden="true"><div className="public-home-decoration public-home-decoration-copper" /><div className="public-home-decoration public-home-decoration-green" /></div>
          <div className="public-home-instrument relative ml-auto max-w-[640px]" data-hero-instrument="true">
            <div className="public-home-instrument-head"><span className="font-mono text-[10px] uppercase tracking-[0.18em] text-white/45">Signal field / live readout</span><span className="inline-flex items-center gap-2 rounded-full border border-white/10 px-2.5 py-1 font-mono text-[10px] text-[#8FE0A7]"><span className="h-1.5 w-1.5 rounded-full bg-[#8FE0A7]" /> Active</span></div>
            <div className="public-home-signal-path" aria-label="Signal path from visitor context to adapted experience">
              <div className="public-home-signal-stage public-stage-observe" data-public-signal-step="observe"><div className="public-stage-icon"><Globe2 className="h-5 w-5" /></div><div className="min-w-0"><p className="font-mono text-[10px] uppercase tracking-[0.14em] text-white/45">01 · Observe</p><p className="mt-2 text-xl font-semibold tracking-[-0.04em] text-white">High-intent visitor</p><p className="mt-1 text-xs leading-5 text-white/50">Returning from a target account</p></div></div>
              <ArrowRight className="public-signal-arrow" aria-hidden="true" />
              <div className="public-home-signal-stage public-stage-activate" data-public-signal-step="decide"><div className="public-stage-icon"><Waypoints className="h-5 w-5" /></div><div className="min-w-0"><p className="font-mono text-[10px] uppercase tracking-[0.14em] text-white/45">02 · Decide</p><p className="mt-2 text-xl font-semibold tracking-[-0.04em] text-white">Rule matched</p><p className="mt-1 text-xs leading-5 text-white/50">Enterprise proof point selected</p></div></div>
              <ArrowRight className="public-signal-arrow" aria-hidden="true" />
              <div className="public-home-signal-stage public-stage-positive" data-public-signal-step="adapt"><div className="public-stage-icon"><Sparkles className="h-5 w-5" /></div><div className="min-w-0"><p className="font-mono text-[10px] uppercase tracking-[0.14em] text-white/45">03 · Adapt</p><p className="mt-2 text-xl font-semibold tracking-[-0.04em] text-white">Experience adapted</p><p className="mt-1 text-xs leading-5 text-white/50">The next action is now contextual</p></div></div>
            </div>
            <div className="public-home-pressure"><div><p className="font-mono text-[10px] uppercase tracking-[0.15em] text-white/45">Opportunity pressure</p><p className="mt-2 text-[clamp(2rem,4vw,3.25rem)] font-semibold tracking-[-0.07em] text-white">Needs attention</p></div><div className="public-pressure-meter"><span className="public-pressure-fill" /></div><div className="flex justify-between font-mono text-[9px] uppercase tracking-[0.15em] text-white/35"><span>Stable</span><span>Pressure</span></div></div>
            <div className="public-home-path"><div className="min-w-0"><p className="font-mono text-[10px] uppercase tracking-[0.15em] text-white/40">Current path</p><p className="mt-2 break-words text-sm leading-6 text-white">Returning enterprise visitor <span className="mx-2 text-white/30" aria-hidden="true">→</span> Social proof variant</p></div><span className="shrink-0 rounded-full bg-[#8FE0A7]/15 px-2.5 py-1 text-[10px] font-semibold text-[#8FE0A7]">MATCHED</span></div>
            <div className="flex items-center justify-between pt-4 font-mono text-[10px] uppercase tracking-[0.14em] text-white/35"><span>Signals → decisions → experiences</span><span>CHURNAUT / 2026</span></div>
          </div>
        </div>
      </section>

      <section className="public-home-journey border-y border-[var(--field-line)] bg-[var(--field-surface)]" aria-labelledby="journey-heading"><div className="mx-auto w-full max-w-[1440px] px-6 py-14 sm:px-10 lg:px-14 lg:py-20"><div className="max-w-xl"><p className="font-mono text-[10px] font-semibold uppercase tracking-[0.18em] text-[var(--signal-primary)]">The signal journey</p><h2 id="journey-heading" className="mt-4 text-4xl font-semibold tracking-[-0.06em] sm:text-5xl">From context to confident action.</h2></div><ol className="public-home-steps mt-12">{steps.map(({ number, title, copy, icon: Icon, tone }) => <li key={number} className="public-home-step"><div className={`public-step-marker ${tone}`}><Icon className="h-5 w-5" aria-hidden="true" /></div><div className="min-w-0"><p className="font-mono text-[10px] tracking-[0.16em] text-[var(--field-ink-muted)]">{number}</p><h3 className="mt-3 text-2xl font-semibold tracking-[-0.05em]">{title}</h3><p className="mt-3 max-w-[32ch] text-sm leading-6 text-[var(--field-ink-secondary)]">{copy}</p></div>{number !== '03' ? <ArrowRight className="public-step-connector" aria-hidden="true" /> : null}</li>)}</ol></div></section>

      <section className="public-home-proof mx-auto grid w-full max-w-[1440px] gap-12 px-6 py-20 sm:px-10 lg:grid-cols-[0.7fr_1.3fr] lg:gap-20 lg:px-14 lg:py-28"><div className="lg:pt-8"><p className="font-mono text-[10px] font-semibold uppercase tracking-[0.18em] text-[var(--signal-primary)]">A calmer operating system</p><h2 className="mt-5 max-w-[10ch] text-5xl font-semibold leading-[0.94] tracking-[-0.07em] sm:text-6xl">Revenue teams deserve better signals.</h2><p className="mt-7 max-w-[34ch] text-base leading-7 text-[var(--field-ink-secondary)]">Not another dashboard that asks you to stare harder. A workspace that tells you what changed, why it matters, and what to do next.</p><Link href="/signup" className="mt-8 inline-flex items-center gap-2 text-sm font-semibold text-[var(--signal-primary)]">See how it works <ArrowRight className="h-4 w-4" /></Link></div><div className="public-home-workflow"><div className="public-workflow-head"><div><p className="font-mono text-[10px] uppercase tracking-[0.15em] text-white/45">Signal → move</p><p className="mt-3 text-2xl font-semibold tracking-[-0.04em] text-white sm:text-3xl">Your existing stack, finally acting in concert.</p></div><BarChart3 className="h-6 w-6 shrink-0 text-[#A7D8EB]" aria-hidden="true" /></div><div className="public-workflow-ledger"><div className="public-workflow-row"><span className="public-workflow-index">01</span><div><p className="text-sm font-semibold text-white">Web intent</p><p className="mt-1 text-xs leading-5 text-white/50">A target account returns to the pricing page.</p></div><span className="public-workflow-tag public-tag-observe">OBSERVED</span></div><div className="public-workflow-row"><span className="public-workflow-index">02</span><div><p className="text-sm font-semibold text-white">Routing logic</p><p className="mt-1 text-xs leading-5 text-white/50">A rule selects the right proof and owner.</p></div><span className="public-workflow-tag public-tag-activate">DECIDED</span></div><div className="public-workflow-row"><span className="public-workflow-index">03</span><div><p className="text-sm font-semibold text-white">Personalized path</p><p className="mt-1 text-xs leading-5 text-white/50">The next experience meets the moment.</p></div><span className="public-workflow-tag public-tag-positive">ADAPTED</span></div></div><div className="mt-7 flex items-center gap-2 text-xs text-white/50"><ArrowDownRight className="h-4 w-4 text-[#F4C96B]" /> Less guesswork. More useful moments.</div></div></section>

      <section className="public-home-cta border-y border-[var(--field-line)] bg-[var(--field-raised)]"><div className="mx-auto flex w-full max-w-[1440px] flex-col gap-7 px-6 py-14 sm:px-10 md:flex-row md:items-center md:justify-between lg:px-14 lg:py-16"><div><p className="font-mono text-[10px] font-semibold uppercase tracking-[0.18em] text-[var(--signal-primary)]">Ready when you are</p><h2 className="mt-3 text-3xl font-semibold tracking-[-0.05em] sm:text-4xl">Give your next signal somewhere to go.</h2></div><Link href="/signup" className="inline-flex min-h-12 shrink-0 items-center justify-center gap-3 rounded-full bg-[var(--field-ink)] px-6 text-sm font-semibold text-white shadow-lg shadow-black/10 transition motion-safe:hover:-translate-y-0.5 hover:bg-[var(--signal-primary)]">Initialize workspace <ArrowRight className="h-4 w-4" /></Link></div></section>

      <footer className="border-t border-[var(--field-line)]"><div className="mx-auto flex w-full max-w-[1440px] flex-col gap-4 px-6 py-7 text-xs text-[var(--field-ink-muted)] sm:flex-row sm:items-center sm:justify-between sm:px-10 lg:px-14"><span>© 2026 Churnaut. Signals in. Revenue out.</span><div className="flex items-center gap-5"><Link href="/snippet.js" className="transition hover:text-[var(--field-ink)]">SDK</Link><Link href="/login" className="transition hover:text-[var(--field-ink)]">Sign in</Link><Link href="/signup" className="font-semibold text-[var(--signal-primary)] transition hover:text-[var(--signal-primary-strong)]">Get started <span aria-hidden="true">→</span></Link></div></div></footer>
    </main>
  );
}
