'use client';

import { useEffect, useState } from 'react';
import Link from 'next/link';
import { PageHeader } from '@/components/dashboard/PageHeader';
import { SectionHeader as BaseSectionHeader } from '@/components/dashboard/SectionHeader';
function SectionHeader({ title, description }: { title: string; description?: string; eyebrow?: string }) { return <BaseSectionHeader title={title} description={description} />; }
import { Surface } from '@/components/dashboard/Surface';
import { StatusBadge } from '@/components/dashboard/StatusBadge';

type CrmStatus = { connected: boolean; crm_type: string | null };
type CalendlyStatus = { connected: boolean; connected_at: string | null };
const fields = ['prospect_name', 'prospect_email', 'company_name', 'job_title', 'assigned_rep', 'signal_type'];
const outreach = [
  { key: 'instantly', name: 'Instantly', description: 'Auto-enrich sessions from active Instantly campaigns and sequences.', signal: 'Instantly', setup: ['Go to Campaign > Integrations in Instantly.', 'Add a new webhook triggered on Email Sent.', 'Paste the Webhook URL above.', 'Use {{churnaut_link}} as a custom variable in templates.'] },
  { key: 'smartlead', name: 'Smartlead', description: 'Pull prospect data from Smartlead campaigns into tracked link sessions.', signal: 'Smartlead', setup: ['Go to Settings > Webhooks in Smartlead.', 'Create a webhook for the Email Sent event.', 'Paste the Webhook URL above.', 'Reference {{churnaut_link}} in sequences.'] },
  { key: 'apollo', name: 'Apollo', description: 'Sync Apollo sequence activity and contact data for real-time personalization.', signal: 'Apollo', setup: ['Go to Integrations > Webhooks in Apollo settings.', 'Create a webhook targeting active sequence events.', 'Paste the Webhook URL above.', 'Use the custom field {{churnaut_link}} in templates.'] },
  { key: 'lemlist', name: 'Lemlist', description: 'Enrich sessions from Lemlist campaigns with prospect and sequence context.', signal: 'Lemlist', setup: ['Add a Webhook/API node in a Lemlist campaign workflow.', 'Set method to POST, targeting the URL above.', 'Paste the Webhook URL above.', 'Reference the variable {{churnaut_link}} in templates.'] },
  { key: 'zapier', name: 'Zapier', description: 'Send prospect data from any Zap directly to Churnaut and generate a personalized tracked link automatically.', signal: 'Zapier', setup: ['In Zapier, create a new Zap and choose your trigger app (for example Google Sheets, HubSpot, or Instantly).', 'Add a Webhooks by Zapier action → POST.', 'Paste your Churnaut webhook URL above as the endpoint.', 'Map prospect_name, prospect_email, company_name, job_title, assigned_rep, and signal_type.', 'Set signal_type to "Zapier" for correct analytics attribution.', 'Add {{churnaut_link}} as a custom variable in your email template.'] },
  { key: 'make', name: 'Make', description: 'Connect any Make scenario to Churnaut via webhook and auto-generate tracked links.', signal: 'Make', setup: ['In Make, open your scenario and add an HTTP module → Make a request.', 'Set method to POST and use the plain Churnaut webhook endpoint above; if your provider supports custom headers, add Authorization: Bearer <your webhook secret>.', 'Set the Content-Type header to application/json.', 'Map prospect_name, prospect_email, company_name, job_title, assigned_rep, and signal_type in the request body.', 'Set signal_type to "Make" for correct analytics attribution.', 'Use the churnaut_link value from the response in your downstream email or CRM module.'] },
] as const;

export default function IntegrationsPage() {
  const [plan, setPlan] = useState('starter');
  const [crmStatus, setCrmStatus] = useState<CrmStatus | null>(null);
  const [calendlyStatus, setCalendlyStatus] = useState<CalendlyStatus | null>(null);
  const [crmLoading, setCrmLoading] = useState(true);
  const [calendlyLoading, setCalendlyLoading] = useState(true);
  const [planLoading, setPlanLoading] = useState(true);
  const [planError, setPlanError] = useState(false);
  const [crmError, setCrmError] = useState(false);
  const [calendlyError, setCalendlyError] = useState(false);
  const [copiedKey, setCopiedKey] = useState<string | null>(null);
  const [openExpectedFields, setOpenExpectedFields] = useState<Record<string, boolean>>({});

  useEffect(() => {
    fetch('/api/oauth/crm').then((res) => res.ok ? res.json() : Promise.reject(new Error('status'))).then(setCrmStatus).catch(() => setCrmError(true)).finally(() => setCrmLoading(false));
    fetch('/api/oauth/calendly/status').then((res) => res.ok ? res.json() : Promise.reject(new Error('status'))).then(setCalendlyStatus).catch(() => setCalendlyError(true)).finally(() => setCalendlyLoading(false));
    fetch('/api/client').then((res) => res.ok ? res.json() : Promise.reject(new Error('plan'))).then((data) => data.client?.plan && setPlan(data.client.plan)).catch(() => setPlanError(true)).finally(() => setPlanLoading(false));
  }, []);

  const webhookUrl = typeof window !== 'undefined' ? `${window.location.origin}/api/webhook` : '/api/webhook';
  const copy = (text: string, key: string) => { navigator.clipboard.writeText(text); setCopiedKey(key); window.setTimeout(() => setCopiedKey(null), 2000); };
  const toggle = (key: string) => setOpenExpectedFields((prev) => ({ ...prev, [key]: !prev[key] }));
  const crmCards = [
    ['HubSpot', 'hubspot', 'Sync deals, owners, pipeline stages, and contact enrichment.', '/dashboard/integrations/crm/hubspot', 'Disconnected'],
    ['Pipedrive', 'pipedrive', 'Webhook intake is available; native Scout pipeline sync is not yet available.', null, 'Webhook Only'],
    ['Zoho CRM', 'zoho', 'Webhook intake is available; native Scout pipeline sync is not yet available.', null, 'Webhook Only'],
    ['Close', 'close', 'Webhook intake is available; native Scout pipeline sync is not yet available.', null, 'Webhook Only'],
    ['Salesforce', 'salesforce', 'Connect Salesforce Sales Cloud to map opportunity objects and lifecycle stages.', '/dashboard/integrations/crm/salesforce', 'Coming Soon'],
    ['Attio', 'attio', 'Sync Attio workspace records, pipelines, and contact attributes in real time.', '/dashboard/integrations/crm/attio', 'Coming Soon'],
  ] as const;

  return <div className="dashboard-integrations space-y-6">
    <PageHeader eyebrow="Signal Field · Connection fabric" title="Integrations" description="Connect the systems that feed Churnaut’s personalization signals." />
    <Surface className="p-6 md:p-8"><SectionHeader eyebrow="CRM platforms" title="Connection map" description="Scout is currently enriched by the HubSpot adapter. Other providers remain clearly labelled by capability." /><div className="mt-6 grid gap-5 md:grid-cols-2 xl:grid-cols-3">{crmCards.map(([name, key, description, href, state]) => { const connected = crmStatus?.connected && crmStatus.crm_type === key; const gated = !planLoading && !planError && plan === 'starter' && ['pipedrive', 'zoho', 'close'].includes(key); const liveState = key === 'hubspot' ? (crmLoading ? 'Loading' : crmError ? 'Status unavailable' : connected ? 'Connected' : 'Disconnected') : gated ? 'Growth Plan' : state; const card = <div className={`h-full rounded-2xl border p-6 flex flex-col gap-4 ${gated ? 'opacity-75' : ''} ${connected ? 'border-[#165B40] ring-2 ring-[#165B40]/15' : 'border-slate-200/90 hover:border-slate-300'} bg-white shadow-xs`}><div className="flex items-start justify-between gap-3"><h2 className="font-sans text-base font-bold text-slate-900">{name}</h2><StatusBadge tone={connected ? 'success' : state === 'Webhook Only' ? 'warning' : state === 'Coming Soon' ? 'neutral' : 'neutral'}>{liveState}</StatusBadge></div><p className="text-sm leading-relaxed text-slate-600 flex-1">{description}</p>{href ? <span className="dashboard-button-secondary w-full justify-center">MANAGE →</span> : <span className="rounded-full border border-slate-200 px-3 py-2 text-center text-[10px] font-mono uppercase tracking-wide text-slate-400">WEBHOOK ONLY — ADAPTER PENDING</span>}</div>; return href ? <Link key={key} href={href} className="block">{card}</Link> : <div key={key} className="relative">{card}{gated && <Link href="/dashboard/billing" className="absolute inset-x-5 bottom-5 text-center text-xs font-semibold text-[#165B40]">Upgrade to unlock →</Link>}</div>; })}</div></Surface>
    <Surface className="p-6 md:p-8"><SectionHeader eyebrow="Outbound & outreach" title="Event sources" description="Use the plain /api/webhook endpoint. New setups should use an Authorization header or signed request headers." /><div className="mt-6 rounded-2xl border border-slate-200 bg-slate-50/70 p-5"><div className="flex flex-col gap-3 sm:flex-row sm:items-end"><div className="min-w-0 flex-1"><label htmlFor="webhook-endpoint" className="dashboard-field-label">Shared webhook endpoint</label><input id="webhook-endpoint" readOnly value={webhookUrl} className="dashboard-input mt-2 w-full font-mono text-xs bg-white" /></div><button type="button" onClick={() => copy(webhookUrl, 'endpoint')} className="dashboard-button-primary shrink-0">{copiedKey === 'endpoint' ? 'COPIED!' : 'COPY ENDPOINT'}</button></div><p className="mt-3 text-xs leading-5 text-slate-500">Send the secret in an Authorization header or signed request header. Do not put credentials in the URL.</p></div><div className="mt-6 grid gap-5 md:grid-cols-2 xl:grid-cols-3">{outreach.map((source) => { const id = `expected-${source.key}`; const open = !!openExpectedFields[source.key]; return <div key={source.key} className="rounded-2xl border border-slate-200/90 bg-white p-6 space-y-4 shadow-xs"><div className="flex items-start justify-between gap-3"><h2 className="font-sans text-base font-bold text-slate-900">{source.name}</h2><StatusBadge tone="success">Ready</StatusBadge></div><p className="text-sm leading-relaxed text-slate-600">{source.description}</p><div className="rounded-xl border border-slate-200 bg-slate-50/80 p-3.5 text-xs text-slate-600"><p className="font-semibold text-slate-900">Setup instructions</p><ol className="mt-2 list-decimal space-y-1.5 pl-4">{source.setup.map((step) => <li key={step}>{step}</li>)}</ol></div><div className="rounded-xl border border-slate-200 overflow-hidden"><button id={`expected-trigger-${source.key}`} type="button" aria-expanded={open} aria-controls={id} onClick={() => toggle(source.key)} className="w-full flex items-center justify-between p-3 text-left text-xs font-semibold text-slate-700 hover:text-slate-900 hover:bg-slate-50 transition-colors"><span>Expected Payload Fields</span><span aria-hidden="true">{open ? '−' : '+'}</span></button>{open && <div id={id} role="region" aria-labelledby={`expected-trigger-${source.key}`} className="border-t border-slate-200 p-3.5 bg-slate-50/50"><ul className="grid gap-1.5 text-xs text-slate-600">{fields.map((field) => <li key={field}><code className="text-[#165B40] font-mono text-[11px] font-semibold">{field}</code>{field === 'signal_type' && <span className="text-amber-600"> · must be “{source.signal}”</span>}</li>)}</ul></div>}</div></div>; })}</div></Surface>
    <Surface className="p-6 md:p-8"><SectionHeader eyebrow="Scheduling & automation" title="Calendly and workflow tools" description="Keep scheduling and automation credentials visible, copyable, and free of secrets in URLs." /><div className="mt-6 grid gap-5 md:grid-cols-2"><div className="rounded-2xl border border-slate-200/90 bg-white p-6 flex items-start justify-between gap-4 shadow-xs"><div><h2 className="font-sans text-base font-bold text-slate-900">Calendly</h2><p className="mt-2 text-sm leading-relaxed text-slate-600">OAuth-based calendar embed — route visitors to the right rep’s booking page.</p></div><div className="flex flex-col items-end gap-3 flex-shrink-0"><StatusBadge tone={calendlyStatus?.connected ? 'success' : calendlyLoading ? 'neutral' : calendlyError ? 'danger' : 'neutral'}>{calendlyLoading ? 'Loading' : calendlyError ? 'Status unavailable' : calendlyStatus?.connected ? 'Active' : 'Disconnected'}</StatusBadge><Link href="/dashboard/integrations/calendly" className="dashboard-button-secondary">MANAGE →</Link></div></div><div className="rounded-2xl border border-slate-200/90 bg-white p-6 flex items-start justify-between gap-4 shadow-xs"><div><h2 className="font-sans text-base font-bold text-slate-900">Webhook configuration</h2><p className="mt-2 text-sm leading-relaxed text-slate-600">Manage authorization tokens, field mappings, and ingestion telemetry.</p></div><div className="flex flex-wrap items-center gap-2 flex-shrink-0"><Link href="/dashboard/integrations/webhooks" className="dashboard-button-secondary shrink-0">CONFIGURE →</Link><Link href="/dashboard/snippet" className="dashboard-button-primary shrink-0">INSTALL SNIPPET →</Link></div></div></div></Surface>
  </div>;
}
