'use client';

import { useEffect, useState } from 'react';
import Link from 'next/link';
import { PageHeader } from '@/components/dashboard/PageHeader';
import { SectionHeader as BaseSectionHeader } from '@/components/dashboard/SectionHeader';
function SectionHeader({ title, description }: { title: string; description?: string; eyebrow?: string }) { return <BaseSectionHeader title={title} description={description} />; }
import { Surface } from '@/components/dashboard/Surface';
import { StatusBadge } from '@/components/dashboard/StatusBadge';

type CrmStatus = { connected: boolean; crm_type: string | null };
type CalendlyStatus = { connected: boolean; connected_at: string | null };
const fields = ['prospect_name', 'prospect_email', 'company_name', 'job_title', 'assigned_rep', 'signal_type'];
const outreach = [
  { key: 'instantly', name: 'Instantly', description: 'Auto-enrich sessions from active Instantly campaigns and sequences.', signal: 'Instantly', setup: ['Go to Campaign > Integrations in Instantly.', 'Add a new webhook triggered on Email Sent.', 'Paste the Webhook URL above.', 'Use {{churnaut_link}} as a custom variable in templates.'] },
  { key: 'smartlead', name: 'Smartlead', description: 'Pull prospect data from Smartlead campaigns into tracked link sessions.', signal: 'Smartlead', setup: ['Go to Settings > Webhooks in Smartlead.', 'Create a webhook for the Email Sent event.', 'Paste the Webhook URL above.', 'Reference {{churnaut_link}} in sequences.'] },
  { key: 'apollo', name: 'Apollo', description: 'Sync Apollo sequence activity and contact data for real-time personalization.', signal: 'Apollo', setup: ['Go to Integrations > Webhooks in Apollo settings.', 'Create a webhook targeting active sequence events.', 'Paste the Webhook URL above.', 'Use the custom field {{churnaut_link}} in templates.'] },
  { key: 'lemlist', name: 'Lemlist', description: 'Enrich sessions from Lemlist campaigns with prospect and sequence context.', signal: 'Lemlist', setup: ['Add a Webhook/API node in a Lemlist campaign workflow.', 'Set method to POST, targeting the URL above.', 'Paste the Webhook URL above.', 'Reference the variable {{churnaut_link}} in templates.'] },
  { key: 'zapier', name: 'Zapier', description: 'Send prospect data from any Zap directly to Churnaut and generate a personalized tracked link automatically.', signal: 'Zapier', setup: ['In Zapier, create a new Zap and choose your trigger app (for example Google Sheets, HubSpot, or Instantly).', 'Add a Webhooks by Zapier action → POST.', 'Paste your Churnaut webhook URL above as the endpoint.', 'Map prospect_name, prospect_email, company_name, job_title, assigned_rep, and signal_type.', 'Set signal_type to "Zapier" for correct analytics attribution.', 'Add {{churnaut_link}} as a custom variable in your email template.'] },
  { key: 'make', name: 'Make', description: 'Connect any Make scenario to Churnaut via webhook and auto-generate tracked links.', signal: 'Make', setup: ['In Make, open your scenario and add an HTTP module → Make a request.', 'Set method to POST and use the plain Churnaut webhook endpoint above; if your provider supports custom headers, add Authorization: Bearer <your webhook secret>.', 'Set the Content-Type header to application/json.', 'Map prospect_name, prospect_email, company_name, job_title, assigned_rep, and signal_type in the request body.', 'Set signal_type to "Make" for correct analytics attribution.', 'Use the churnaut_link value from the response in your downstream email or CRM module.'] },
] as const;

export default function IntegrationsPage() {
  const [plan, setPlan] = useState('starter');
  const [crmStatus, setCrmStatus] = useState<CrmStatus | null>(null);
  const [calendlyStatus, setCalendlyStatus] = useState<CalendlyStatus | null>(null);
  const [copiedKey, setCopiedKey] = useState<string | null>(null);
  const [openExpectedFields, setOpenExpectedFields] = useState<Record<string, boolean>>({});

  useEffect(() => {
    fetch('/api/oauth/crm').then((res) => res.json()).then(setCrmStatus).catch(() => {});
    fetch('/api/oauth/calendly/status').then((res) => res.json()).then(setCalendlyStatus).catch(() => {});
    fetch('/api/client').then((res) => res.json()).then((data) => data.client?.plan && setPlan(data.client.plan)).catch(() => {});
  }, []);

  const webhookUrl = typeof window !== 'undefined' ? `${window.location.origin}/api/webhook` : '/api/webhook';
  const copy = (text: string, key: string) => { navigator.clipboard.writeText(text); setCopiedKey(key); window.setTimeout(() => setCopiedKey(null), 2000); };
  const toggle = (key: string) => setOpenExpectedFields((prev) => ({ ...prev, [key]: !prev[key] }));
  const crmCards = [
    ['HubSpot', 'hubspot', 'Sync deals, owners, pipeline stages, and contact enrichment.', '/dashboard/integrations/crm/hubspot', 'Disconnected'],
    ['Pipedrive', 'pipedrive', 'Webhook intake is available; native Scout pipeline sync is not yet available.', null, 'Webhook Only'],
    ['Zoho CRM', 'zoho', 'Webhook intake is available; native Scout pipeline sync is not yet available.', null, 'Webhook Only'],
    ['Close', 'close', 'Webhook intake is available; native Scout pipeline sync is not yet available.', null, 'Webhook Only'],
    ['Salesforce', 'salesforce', 'Connect Salesforce Sales Cloud to map opportunity objects and lifecycle stages.', '/dashboard/integrations/crm/salesforce', 'Coming Soon'],
    ['Attio', 'attio', 'Sync Attio workspace records, pipelines, and contact attributes in real time.', '/dashboard/integrations/crm/attio', 'Coming Soon'],
  ] as const;

  return <div className="space-y-6">
    <PageHeader eyebrow="Signal Room · Connection map" title="Integrations" description="Connect the systems that feed Churnaut’s personalization signals." />
    <Surface><SectionHeader eyebrow="CRM platforms" title="Connection map" description="Scout is currently enriched by the HubSpot adapter. Other providers remain clearly labelled by capability." /><div className="mt-5 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{crmCards.map(([name, key, description, href, state]) => { const connected = crmStatus?.connected && crmStatus.crm_type === key; const gated = plan === 'starter' && ['pipedrive', 'zoho', 'close'].includes(key); const card = <div className={`h-full rounded-[var(--radius-md)] border p-5 flex flex-col gap-4 ${gated ? 'opacity-75' : ''} ${connected ? 'border-[var(--green)]/40' : 'border-[var(--border-subtle)]'} bg-[var(--bg-elevated)]/55`}><div className="flex items-start justify-between gap-3"><h2 className="font-mono text-sm font-semibold">{name}</h2><StatusBadge tone={connected ? 'success' : state === 'Webhook Only' ? 'warning' : state === 'Coming Soon' ? 'neutral' : 'neutral'}>{connected ? 'Connected' : gated ? 'Growth Plan' : state}</StatusBadge></div><p className="text-sm leading-6 text-[var(--text-secondary)] flex-1">{description}</p>{href ? <span className="dashboard-button-secondary w-full justify-center">MANAGE →</span> : <span className="rounded border border-[var(--border-subtle)] px-3 py-2 text-center text-[10px] font-mono uppercase tracking-wide text-[var(--text-muted)]">WEBHOOK ONLY — ADAPTER PENDING</span>}</div>; return href ? <Link key={key} href={href} className="block">{card}</Link> : <div key={key} className="relative">{card}{gated && <Link href="/dashboard/billing" className="absolute inset-x-5 bottom-5 text-center text-xs font-semibold text-[var(--accent)]">Upgrade to unlock →</Link>}</div>; })}</div></Surface>
    <Surface><SectionHeader eyebrow="Outbound & outreach" title="Event sources" description="Use the plain /api/webhook endpoint. New setups should use an Authorization header or signed request headers." /><div className="mt-5 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{outreach.map((source) => { const id = `expected-${source.key}`; const open = !!openExpectedFields[source.key]; return <div key={source.key} className="rounded-[var(--radius-md)] border border-[var(--border-subtle)] bg-[var(--bg-elevated)]/55 p-5 space-y-4"><div className="flex items-start justify-between gap-3"><h2 className="font-mono text-sm font-semibold">{source.name}</h2><StatusBadge tone="success">Ready</StatusBadge></div><p className="text-sm leading-6 text-[var(--text-secondary)]">{source.description}</p><div className="space-y-2"><label htmlFor={`webhook-${source.key}`} className="dashboard-field-label">Webhook URL</label><div className="flex gap-2"><input id={`webhook-${source.key}`} readOnly value={webhookUrl} className="dashboard-input min-w-0 flex-1 font-mono text-[11px]" /><button type="button" onClick={() => copy(webhookUrl, source.key)} className="dashboard-button-primary shrink-0">{copiedKey === source.key ? 'COPIED!' : 'COPY'}</button></div></div><div className="rounded border border-[var(--border-subtle)]/70 bg-[var(--bg-surface)]/50 p-3 text-xs text-[var(--text-secondary)]"><p className="font-semibold text-[var(--text-primary)]">Setup instructions</p><ol className="mt-2 list-decimal space-y-1 pl-4">{source.setup.map((step) => <li key={step}>{step}</li>)}</ol></div><div className="rounded border border-[var(--border-subtle)]/70 overflow-hidden"><button id={`expected-trigger-${source.key}`} type="button" aria-expanded={open} aria-controls={id} onClick={() => toggle(source.key)} className="w-full flex items-center justify-between p-3 text-left text-xs font-semibold text-[var(--text-secondary)] hover:text-[var(--text-primary)]"><span>Expected Payload Fields</span><span aria-hidden="true">{open ? '−' : '+'}</span></button>{open && <div id={id} role="region" aria-labelledby={`expected-trigger-${source.key}`} className="border-t border-[var(--border-subtle)] p-3"><ul className="grid gap-1 text-xs text-[var(--text-secondary)]">{fields.map((field) => <li key={field}><code className="text-[var(--accent)]">{field}</code>{field === 'signal_type' && <span className="text-[var(--amber)]"> · must be “{source.signal}”</span>}</li>)}</ul></div>}</div></div>; })}</div></Surface>
    <Surface><SectionHeader eyebrow="Scheduling & automation" title="Calendly and workflow tools" description="Keep scheduling and automation credentials visible, copyable, and free of secrets in URLs." /><div className="grid gap-4 md:grid-cols-2"><div className="rounded-[var(--radius-md)] border border-[var(--border-subtle)] bg-[var(--bg-elevated)]/55 p-5 flex items-start justify-between gap-4"><div><h2 className="font-mono text-sm font-semibold">Calendly</h2><p className="mt-2 text-sm leading-6 text-[var(--text-secondary)]">OAuth-based calendar embed — route visitors to the right rep’s booking page.</p></div><div className="flex flex-col items-end gap-3"><StatusBadge tone={calendlyStatus?.connected ? 'success' : 'neutral'}>{calendlyStatus?.connected ? 'Active' : 'Disconnected'}</StatusBadge><Link href="/dashboard/integrations/calendly" className="dashboard-button-secondary">MANAGE →</Link></div></div><div className="rounded-[var(--radius-md)] border border-[var(--border-subtle)] bg-[var(--bg-elevated)]/55 p-5 flex items-start justify-between gap-4"><div><h2 className="font-mono text-sm font-semibold">Webhook configuration</h2><p className="mt-2 text-sm leading-6 text-[var(--text-secondary)]">Manage authorization tokens, field mappings, and ingestion telemetry.</p></div><Link href="/dashboard/integrations/webhooks" className="dashboard-button-secondary shrink-0">CONFIGURE →</Link></div></div></Surface>
  </div>;
}
