'use client';
import { useEffect, useState } from 'react';
import Link from 'next/link';
import { PageHeader } from '@/components/dashboard/PageHeader';
import { Surface } from '@/components/dashboard/Surface';
import { StatusBadge } from '@/components/dashboard/StatusBadge';
type CrmStatus = { connected: boolean; crm_type: string | null; connected_at: string | null };
const formatDate = (value: string | null) => value ? new Date(value).toLocaleString('en-US', { dateStyle: 'medium', timeStyle: 'short' }) : 'N/A';
export default function HubSpotSettingsPage() {
  const [status, setStatus] = useState<CrmStatus | null>(null); const [loading, setLoading] = useState(true); const [statusError, setStatusError] = useState(false); const [disconnecting, setDisconnecting] = useState(false); const [message, setMessage] = useState<{ type: 'success' | 'error'; text: string } | null>(null);
  const loadStatus = () => { setLoading(true); setStatusError(false); fetch('/api/oauth/crm').then((res) => res.ok ? res.json() : Promise.reject(new Error('status'))).then(setStatus).catch(() => setStatusError(true)).finally(() => setLoading(false)); };
  useEffect(() => { loadStatus(); }, []);
  const handleDisconnect = async () => { if (!window.confirm('Are you sure you want to disconnect HubSpot CRM? This will remove all synchronization tokens.')) return; setDisconnecting(true); try { const res = await fetch('/api/oauth/crm', { method: 'DELETE' }); if (!res.ok) throw new Error('Failed to disconnect HubSpot CRM. Please try again.'); setStatus({ connected: false, crm_type: null, connected_at: null }); setMessage({ type: 'success', text: 'HubSpot CRM connection successfully removed.' }); } catch (error) { setMessage({ type: 'error', text: error instanceof Error ? error.message : 'An unexpected error occurred during disconnection.' }); } finally { setDisconnecting(false); } };
  const connected = !!status?.connected && status.crm_type === 'hubspot';
  return <div className="space-y-6"><PageHeader eyebrow="Signal Field · CRM capability" title="HubSpot CRM" description="Map lifecycle stages, synchronize pipeline deals, and assign representative owners dynamically." actions={<Link href="/dashboard/integrations/crm" className="dashboard-button-secondary">← CRM DIRECTORY</Link>} />{message && <div role={message.type === 'error' ? 'alert' : 'status'} aria-live="polite" className="dashboard-surface px-4 py-3 flex items-start justify-between gap-4"><p className="text-sm text-[var(--text-secondary)]">{message.text}</p><button type="button" aria-label="Dismiss integration message" onClick={() => setMessage(null)} className="text-xs text-[var(--text-muted)]">DISMISS</button></div>}<Surface><div className="flex flex-col gap-6"><div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><div className="flex flex-wrap items-center gap-3"><h2 className="font-mono text-sm font-semibold">HubSpot CRM connection</h2><StatusBadge tone={connected ? 'success' : statusError ? 'danger' : 'neutral'}>{loading ? 'Loading' : statusError ? 'Status unavailable' : connected ? 'CONNECTED' : 'DISCONNECTED'}</StatusBadge></div><p className="mt-3 max-w-2xl text-sm leading-6 text-[var(--text-secondary)]">Sync leads, assign sales reps, track deal stage changes, and personalize experiences according to HubSpot lifecycle events.</p></div>{loading ? null : statusError ? <button type="button" onClick={loadStatus} className="dashboard-button-secondary shrink-0">TRY AGAIN</button> : connected ? <button type="button" onClick={handleDisconnect} disabled={disconnecting} className="dashboard-button-danger shrink-0">{disconnecting ? 'DISCONNECTING…' : 'DISCONNECT HUBSPOT'}</button> : <a href="/api/oauth/hubspot" className="dashboard-button-primary shrink-0">CONNECT HUBSPOT</a>}</div>{connected && <dl className="grid gap-4 rounded-[var(--radius-md)] border border-[var(--border-subtle)] bg-[var(--bg-surface)]/60 p-4 sm:grid-cols-2"><div><dt className="dashboard-field-label">CRM provider</dt><dd className="mt-1 text-sm font-mono text-[var(--text-primary)]">HUBSPOT</dd></div><div><dt className="dashboard-field-label">Connection date</dt><dd className="mt-1 text-sm text-[var(--text-secondary)]">{formatDate(status?.connected_at ?? null)}</dd></div><div><dt className="dashboard-field-label">Active scopes</dt><dd className="mt-1 text-xs text-[var(--accent)]">contacts.read, deals.read, companies.read, owners.read</dd></div><div><dt className="dashboard-field-label">Sync status</dt><dd className="mt-1 text-sm text-[var(--green)]">ACTIVE &amp; SYNCED</dd></div></dl>}</div></Surface></div>;
}
