'use client';

import { useEffect, useState } from 'react';
import Link from 'next/link';
import { PageHeader } from '@/components/dashboard/PageHeader';
import { Surface } from '@/components/dashboard/Surface';
import { StatusBadge } from '@/components/dashboard/StatusBadge';

type CalendlyStatus = { connected: boolean; connected_at: string | null };
const formatDate = (value: string | null) => value ? new Date(value).toLocaleString('en-US', { dateStyle: 'medium', timeStyle: 'short' }) : 'N/A';

export default function CalendlySettingsPage() {
  const [status, setStatus] = useState<CalendlyStatus | null>(null); const [loading, setLoading] = useState(true); const [disconnecting, setDisconnecting] = useState(false); const [message, setMessage] = useState<{ type: 'success' | 'error'; text: string } | null>(null);
  useEffect(() => { fetch('/api/oauth/calendly/status').then((res) => res.ok ? res.json() : null).then(setStatus).catch(() => {}).finally(() => setLoading(false)); const params = new URLSearchParams(window.location.search); if (params.get('connected') === 'true') setMessage({ type: 'success', text: 'Calendly integration successfully connected!' }); else if (params.get('error')) setMessage({ type: 'error', text: `Failed to connect to Calendly: ${params.get('error')}` }); }, []);
  const handleDisconnect = async () => { if (!window.confirm('Are you sure you want to disconnect Calendly? This will remove all synchronization tokens.')) return; setDisconnecting(true); try { const res = await fetch('/api/oauth/calendly/status', { method: 'DELETE' }); if (!res.ok) throw new Error('Failed to disconnect Calendly. Please try again.'); setStatus({ connected: false, connected_at: null }); setMessage({ type: 'success', text: 'Calendly connection successfully removed.' }); } catch (error) { setMessage({ type: 'error', text: error instanceof Error ? error.message : 'An unexpected error occurred during disconnection.' }); } finally { setDisconnecting(false); } };
  const connected = !!status?.connected;
  return <div className="space-y-6"><PageHeader eyebrow="Signal Room · Scheduling" title="Calendly" description="Route visitors to the right representative’s booking page with an OAuth-based calendar connection." actions={<Link href="/dashboard/integrations" className="dashboard-button-secondary">← CONNECTION MAP</Link>} />{message && <div role={message.type === 'error' ? 'alert' : 'status'} aria-live="polite" className="dashboard-surface px-4 py-3 flex items-start justify-between gap-4"><p className="text-sm text-[var(--text-secondary)]">{message.text}</p><button type="button" aria-label="Dismiss integration message" onClick={() => setMessage(null)} className="text-xs text-[var(--text-muted)]">DISMISS</button></div>}<Surface><div className="flex flex-col gap-6"><div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><div className="flex flex-wrap items-center gap-3"><h2 className="font-mono text-sm font-semibold">Calendly integration status</h2><StatusBadge tone={connected ? 'success' : 'neutral'}>{connected ? 'CONNECTED' : loading ? 'Loading' : 'DISCONNECTED'}</StatusBadge></div><p className="mt-3 max-w-2xl text-sm leading-6 text-[var(--text-secondary)]">Authenticate Calendly via OAuth to resolve team schedules and route visitors to the appropriate booking page automatically.</p></div>{connected ? <button type="button" onClick={handleDisconnect} disabled={disconnecting} className="dashboard-button-danger shrink-0">{disconnecting ? 'DISCONNECTING…' : 'DISCONNECT CALENDLY'}</button> : <a href="/api/oauth/calendly" className="dashboard-button-primary shrink-0">CONNECT CALENDLY</a>}</div>{connected && <dl className="grid gap-4 rounded-[var(--radius-md)] border border-[var(--border-subtle)] bg-[var(--bg-surface)]/60 p-4 sm:grid-cols-2"><div><dt className="dashboard-field-label">Integration</dt><dd className="mt-1 text-sm font-mono text-[var(--text-primary)]">CALENDLY</dd></div><div><dt className="dashboard-field-label">Connection date</dt><dd className="mt-1 text-sm text-[var(--text-secondary)]">{formatDate(status?.connected_at ?? null)}</dd></div><div><dt className="dashboard-field-label">Status</dt><dd className="mt-1 text-sm text-[var(--green)]">ACTIVE</dd></div></dl>}</div></Surface></div>;
}
