-- Privacy-safe operational monitoring state. Service role only.
CREATE TABLE IF NOT EXISTS public.ops_events (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(), created_at timestamptz NOT NULL DEFAULT now(),
  environment text NOT NULL DEFAULT 'production', component text NOT NULL, event_code text NOT NULL,
  severity text NOT NULL CHECK (severity IN ('info','warning','error','critical')),
  client_id uuid REFERENCES public.clients(id) ON DELETE SET NULL, metadata jsonb NOT NULL DEFAULT '{}'
);
CREATE TABLE IF NOT EXISTS public.service_heartbeats (
  service_name text PRIMARY KEY, last_attempt_at timestamptz NOT NULL DEFAULT now(), last_success_at timestamptz,
  status text NOT NULL DEFAULT 'ok' CHECK (status IN ('ok','failed','paused')), metadata jsonb NOT NULL DEFAULT '{}', updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS public.ops_alert_state (
  alert_key text PRIMARY KEY, component text NOT NULL, severity text NOT NULL, status text NOT NULL DEFAULT 'open' CHECK (status IN ('open','resolved')),
  summary text NOT NULL, first_seen_at timestamptz NOT NULL DEFAULT now(), last_seen_at timestamptz NOT NULL DEFAULT now(), occurrence_count integer NOT NULL DEFAULT 1,
  resolved_at timestamptz, last_notified_at timestamptz, notification_claimed_at timestamptz, metadata jsonb NOT NULL DEFAULT '{}'
);
CREATE INDEX IF NOT EXISTS idx_ops_events_code_created ON public.ops_events(event_code, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_ops_events_component_created ON public.ops_events(component, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_ops_events_client_created ON public.ops_events(client_id, created_at DESC);
ALTER TABLE public.ops_events ENABLE ROW LEVEL SECURITY; ALTER TABLE public.service_heartbeats ENABLE ROW LEVEL SECURITY; ALTER TABLE public.ops_alert_state ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.ops_events, public.service_heartbeats, public.ops_alert_state FROM PUBLIC, anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.ops_events, public.service_heartbeats, public.ops_alert_state TO service_role;
CREATE OR REPLACE FUNCTION public.touch_service_heartbeat(service_name_input text, status_input text, metadata_input jsonb DEFAULT '{}') RETURNS void LANGUAGE sql SECURITY DEFINER SET search_path=public,pg_temp AS $$ INSERT INTO service_heartbeats(service_name,last_attempt_at,last_success_at,status,metadata,updated_at) VALUES(service_name_input,now(),CASE WHEN status_input='ok' THEN now() ELSE NULL END,status_input,COALESCE(metadata_input,'{}'),now()) ON CONFLICT(service_name) DO UPDATE SET last_attempt_at=now(),last_success_at=CASE WHEN status_input='ok' THEN now() ELSE service_heartbeats.last_success_at END,status=status_input,metadata=COALESCE(metadata_input,'{}'),updated_at=now(); $$;
CREATE OR REPLACE FUNCTION public.touch_service_attempt(service_name_input text, metadata_input jsonb DEFAULT '{}') RETURNS void LANGUAGE sql SECURITY DEFINER SET search_path=public,pg_temp AS $$ INSERT INTO service_heartbeats(service_name,last_attempt_at,status,metadata,updated_at) VALUES(service_name_input,now(),'failed',COALESCE(metadata_input,'{}'),now()) ON CONFLICT(service_name) DO UPDATE SET last_attempt_at=now(),status=CASE WHEN service_heartbeats.status='paused' THEN 'paused' ELSE 'failed' END,metadata=COALESCE(metadata_input,'{}'),updated_at=now(); $$;
CREATE OR REPLACE FUNCTION public.reconcile_ops_alert(alert_key_input text, component_input text, severity_input text, summary_input text, active_input boolean, metadata_input jsonb DEFAULT '{}') RETURNS public.ops_alert_state LANGUAGE plpgsql SECURITY DEFINER SET search_path=public,pg_temp AS $$ DECLARE r public.ops_alert_state; BEGIN INSERT INTO ops_alert_state(alert_key,component,severity,status,summary,resolved_at,metadata) VALUES(alert_key_input,component_input,severity_input,CASE WHEN active_input THEN 'open' ELSE 'resolved' END,summary_input,CASE WHEN active_input THEN NULL ELSE now() END,COALESCE(metadata_input,'{}')) ON CONFLICT(alert_key) DO UPDATE SET component=EXCLUDED.component,severity=EXCLUDED.severity,summary=EXCLUDED.summary,status=CASE WHEN active_input THEN 'open' ELSE 'resolved' END,last_seen_at=CASE WHEN active_input THEN now() ELSE ops_alert_state.last_seen_at END,occurrence_count=ops_alert_state.occurrence_count+CASE WHEN active_input THEN 1 ELSE 0 END,resolved_at=CASE WHEN active_input THEN NULL ELSE COALESCE(ops_alert_state.resolved_at, now()) END,metadata=EXCLUDED.metadata RETURNING * INTO r; RETURN r; END; $$;
CREATE OR REPLACE FUNCTION public.claim_ops_alert_notification(alert_key_input text, cooldown_minutes integer DEFAULT 30) RETURNS boolean LANGUAGE plpgsql SECURITY DEFINER SET search_path=public,pg_temp AS $$ DECLARE affected integer; BEGIN UPDATE ops_alert_state SET notification_claimed_at=now() WHERE alert_key=alert_key_input AND status='open' AND (last_notified_at IS NULL OR last_notified_at < now()-make_interval(mins=>cooldown_minutes)) AND (notification_claimed_at IS NULL OR notification_claimed_at < now()-interval '10 minutes'); GET DIAGNOSTICS affected=ROW_COUNT; RETURN affected > 0; END; $$;
CREATE OR REPLACE FUNCTION public.complete_ops_alert_notification(alert_key_input text, sent_input boolean) RETURNS void LANGUAGE sql SECURITY DEFINER SET search_path=public,pg_temp AS $$ UPDATE ops_alert_state SET last_notified_at=CASE WHEN sent_input THEN now() ELSE last_notified_at END,notification_claimed_at=NULL WHERE alert_key=alert_key_input; $$;
CREATE OR REPLACE FUNCTION public.purge_ops_monitoring(events_days integer DEFAULT 30, resolved_alert_days integer DEFAULT 90) RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path=public,pg_temp AS $$ BEGIN IF events_days<7 OR events_days>365 OR resolved_alert_days<30 OR resolved_alert_days>730 THEN RAISE EXCEPTION 'Retention outside bounds'; END IF; DELETE FROM ops_events WHERE created_at < now()-make_interval(days=>events_days); DELETE FROM ops_alert_state WHERE status='resolved' AND resolved_at < now()-make_interval(days=>resolved_alert_days); END; $$;
REVOKE ALL ON FUNCTION public.touch_service_heartbeat(text,text,jsonb), public.touch_service_attempt(text,jsonb), public.reconcile_ops_alert(text,text,text,text,boolean,jsonb), public.claim_ops_alert_notification(text,integer), public.complete_ops_alert_notification(text,boolean), public.purge_ops_monitoring(integer,integer) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.touch_service_heartbeat(text,text,jsonb), public.touch_service_attempt(text,jsonb), public.reconcile_ops_alert(text,text,text,text,boolean,jsonb), public.claim_ops_alert_notification(text,integer), public.complete_ops_alert_notification(text,boolean), public.purge_ops_monitoring(integer,integer) TO service_role;
